version: '3.6'
services:
    traefik:
        image: traefik:1.7
        command: |
            --accesslog \
            --api \
            --metrics \
            --metrics.prometheus \
            --metrics.prometheus.entryPoint="traefik" \
            --web \
            --docker \
            --docker.watch \
            --docker.network=traefik \
            --docker.exposedbydefault=false \
            --entryPoints="Name:https Address::443 TLS" \
            --entryPoints="Name:http Address::80 Redirect.EntryPoint:https" \
            --defaultentrypoints="http,https"
            --acme \
            --acme.email="${LE_EMAIL:-le@sikademo.com}" \
            --acme.storage="/acme-data/acme.json" \
            --acme.entryPoint="https" \
            --acme.onHostRule=true \
            --acme.httpChallenge.entryPoint="http"
        userns_mode: host
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./acme-data:/acme-data
        networks:
            - traefik
networks:
    traefik:
        name: traefik
